#include "pointcloud_clustering.hpp"

#include <algorithm>
#include <cctype>
#include <Eigen/Dense>
#include <geometry_msgs/msg/point32.hpp>
#include <geometry_msgs/msg/polygon.hpp>
#include <geometry_msgs/msg/transform_stamped.hpp>
#include <pcl/common/transforms.h>
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/surface/concave_hull.h>
#include <pcl/surface/convex_hull.h>
#include <tf2/LinearMath/Matrix3x3.h>
#include <tf2/LinearMath/Quaternion.h>
#include <tf2/exceptions.h>

#include "path_planning_dynamic/msg/obstacle.hpp"

namespace
{
constexpr double kDefaultConcaveAlpha = 0.15;

// ANSI color escape codes used by ROS log messages.
constexpr const char *kGreen = "\033[1;32m";
constexpr const char *kRed = "\033[1;31m";
constexpr const char *kYellow = "\033[1;33m";
constexpr const char *kBlue = "\033[1;34m";
constexpr const char *kReset = "\033[0m";

/**
 * @brief Normalize hull mode names for parameter validation.
 *
 * Converts the configured HULL_MODE string to lowercase so values like
 * "Convex", "CONVEX", or "convex" are handled consistently.
 *
 * @param mode Hull mode string read from ROS parameters.
 * @return Lowercase hull mode string.
 */
std::string normalizeHullMode(std::string mode)
{
    std::transform(mode.begin(), mode.end(), mode.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return mode;
}

Eigen::Matrix4f transformToMatrix(const geometry_msgs::msg::TransformStamped &transform)
{
    const auto &translation = transform.transform.translation;
    const auto &rotation = transform.transform.rotation;

    tf2::Quaternion quaternion(rotation.x, rotation.y, rotation.z, rotation.w);
    tf2::Matrix3x3 rotation_matrix(quaternion);

    Eigen::Matrix4f matrix = Eigen::Matrix4f::Identity();
    for (int row = 0; row < 3; ++row)
    {
        for (int col = 0; col < 3; ++col)
        {
            matrix(row, col) = static_cast<float>(rotation_matrix[row][col]);
        }
    }
    matrix(0, 3) = static_cast<float>(translation.x);
    matrix(1, 3) = static_cast<float>(translation.y);
    matrix(2, 3) = static_cast<float>(translation.z);
    return matrix;
}

/**
 * @brief Convert a PCL hull point cloud into a closed ROS polygon.
 *
 * Copies each hull vertex into a geometry_msgs polygon and repeats the first
 * point at the end so downstream consumers receive a closed obstacle boundary.
 *
 * @param hull_cloud Hull point cloud generated by PCL.
 * @param polygon Output polygon message.
 * @return true when the hull has enough vertices to form a polygon.
 * @note A valid polygon needs at least three vertices.
 */
bool buildClosedPolygonFromHull(const pcl::PointCloud<pcl::PointXYZ>::Ptr &hull_cloud,
                                geometry_msgs::msg::Polygon &polygon)
{
    if (!hull_cloud || hull_cloud->points.size() < 3)
    {
        return false;
    }

    polygon.points.clear();
    polygon.points.reserve(hull_cloud->points.size() + 1);
    for (const auto &point : hull_cloud->points)
    {
        geometry_msgs::msg::Point32 p;
        p.x = point.x;
        p.y = point.y;
        p.z = 0.0;
        polygon.points.push_back(p);
    }

    polygon.points.push_back(polygon.points.front());
    return true;
}
} // namespace

pointcloud_clustering_node::pointcloud_clustering_node()
    : Node("pointcloud_clustering_node"),
      tf2_buffer_(this->get_clock()),
      tf2_listener_(tf2_buffer_)
{
    this->declare_parameter("CLUSTER_THRESH", 0.0);
    this->declare_parameter("CLUSTER_MAX_SIZE", 0);
    this->declare_parameter("CLUSTER_MIN_SIZE", 0);
    this->declare_parameter("CONCAVE_ALPHA", kDefaultConcaveAlpha);
    this->declare_parameter("FRAME_ID", std::string("base_link"));
    this->declare_parameter("HULL_MODE", std::string("convex"));

    this->get_parameter("CLUSTER_THRESH", CLUSTER_THRESH);
    this->get_parameter("CLUSTER_MAX_SIZE", CLUSTER_MAX_SIZE);
    this->get_parameter("CLUSTER_MIN_SIZE", CLUSTER_MIN_SIZE);
    this->get_parameter("CONCAVE_ALPHA", CONCAVE_ALPHA);
    this->get_parameter("FRAME_ID", FRAME_ID);
    this->get_parameter("HULL_MODE", HULL_MODE);

    HULL_MODE = normalizeHullMode(HULL_MODE);
    if (HULL_MODE != "convex" && HULL_MODE != "concave")
    {
        RCLCPP_WARN(this->get_logger(),
                    "%sInvalid HULL_MODE '%s'. Falling back to 'convex'.%s",
                    kRed, HULL_MODE.c_str(), kReset);
        HULL_MODE = "convex";
    }

    if (CONCAVE_ALPHA <= 0.0)
    {
        RCLCPP_WARN(this->get_logger(),
                    "%sInvalid CONCAVE_ALPHA %.3f. Falling back to %.2f.%s",
                    kRed, CONCAVE_ALPHA, kDefaultConcaveAlpha, kReset);
        CONCAVE_ALPHA = kDefaultConcaveAlpha;
    }

    sub_points_cloud_ = this->create_subscription<sensor_msgs::msg::PointCloud2>("/points_rotated_notground", rclcpp::SensorDataQoS(), std::bind(&pointcloud_clustering_node::pointCloudCallback, this, std::placeholders::_1));
    obstacle_info_publisher_ = this->create_publisher<path_planning_dynamic::msg::ObstacleCollection>("/obstacle_info", 10);

    obstacle_detector = std::make_shared<lidar_obstacle_detector::ObstacleDetector<pcl::PointXYZ>>();

    RCLCPP_INFO(this->get_logger(), "%s----> lidar3d_Clustering_node initialized.%s", kGreen, kReset);
    RCLCPP_INFO(this->get_logger(), "%s----> CLUSTER_THRESH: %f%s", kBlue, CLUSTER_THRESH, kReset);
    RCLCPP_INFO(this->get_logger(), "%s----> CLUSTER_MAX_SIZE: %d%s", kBlue, CLUSTER_MAX_SIZE, kReset);
    RCLCPP_INFO(this->get_logger(), "%s----> CLUSTER_MIN_SIZE: %d%s", kBlue, CLUSTER_MIN_SIZE, kReset);
    RCLCPP_INFO(this->get_logger(), "%s----> HULL_MODE: %s%s", kBlue, HULL_MODE.c_str(), kReset);
    RCLCPP_INFO(this->get_logger(), "%s----> CONCAVE_ALPHA: %f%s", kBlue, CONCAVE_ALPHA, kReset);
}

void pointcloud_clustering_node::pointCloudCallback(const sensor_msgs::msg::PointCloud2::SharedPtr msg)
{
    auto input_cloud = std::make_shared<pcl::PointCloud<pcl::PointXYZ>>();
    pcl::fromROSMsg(*msg, *input_cloud);

    if (input_cloud->empty())
    {
        warnUnsafePerception("Received empty point cloud; no obstacle update published.");
        return;
    }

    pcl::PointCloud<pcl::PointXYZ>::Ptr clustering_cloud;
    if (!transformCloudToFrame(*msg, input_cloud, clustering_cloud))
    {
        return;
    }

    try
    {
        auto clusters = obstacle_detector->clustering(clustering_cloud, CLUSTER_THRESH, CLUSTER_MIN_SIZE, CLUSTER_MAX_SIZE);

        if (!clusters.empty())
        {
            RCLCPP_INFO(this->get_logger(), "%sNumber of clusters: %zu%s", kGreen, clusters.size(), kReset);
            if (HULL_MODE == "concave")
            {
                concave_hull(clusters);
            }
            else
            {
                convex_hull(clusters);
            }
        }
        else
        {
            warnUnsafePerception("No valid clusters detected; no obstacle update published.");
        }
    }
    catch (const std::exception &e)
    {
        warnUnsafePerception(std::string("Error processing point cloud: ") + e.what());
    }
}

bool pointcloud_clustering_node::transformCloudToFrame(
    const sensor_msgs::msg::PointCloud2 &msg,
    const pcl::PointCloud<pcl::PointXYZ>::Ptr &input_cloud,
    pcl::PointCloud<pcl::PointXYZ>::Ptr &output_cloud)
{
    if (msg.header.frame_id.empty())
    {
        warnUnsafePerception("Received point cloud with empty frame_id; no obstacle update published.");
        return false;
    }

    if (msg.header.frame_id == FRAME_ID)
    {
        output_cloud = input_cloud;
        return true;
    }

    try
    {
        const auto sensor_to_obstacle_tf =
            tf2_buffer_.lookupTransform(FRAME_ID, msg.header.frame_id, tf2::TimePointZero);
        output_cloud = std::make_shared<pcl::PointCloud<pcl::PointXYZ>>();
        output_cloud->points.reserve(input_cloud->points.size());
        pcl::transformPointCloud(*input_cloud, *output_cloud, transformToMatrix(sensor_to_obstacle_tf));
        return true;
    }
    catch (const tf2::TransformException &e)
    {
        warnUnsafePerception(
            std::string("Could not transform point cloud from ") + msg.header.frame_id +
            " to " + FRAME_ID + ": " + e.what());
        return false;
    }
}

void pointcloud_clustering_node::convex_hull(const std::vector<pcl::PointCloud<pcl::PointXYZ>::Ptr> &cloud_clusters)
{

    obstacle_collection.obstacles.clear();

    obstacle_collection.header.stamp = this->now();
    obstacle_collection.header.frame_id = FRAME_ID;

    int index = 0;
    obstacle_collection.obstacles.reserve(cloud_clusters.size());
    for (const auto &cluster : cloud_clusters)
    {
        auto convexHull = std::make_shared<pcl::PointCloud<pcl::PointXYZ>>();
        pcl::ConvexHull<pcl::PointXYZ> hull;
        hull.setInputCloud(cluster);
        hull.setDimension(2);
        hull.reconstruct(*convexHull);

        if (convexHull->empty())
        {
            RCLCPP_WARN(this->get_logger(), "%sConvex hull is empty%s", kRed, kReset);
            continue;
        }
        if (hull.getDimension() == 2)
        {
            path_planning_dynamic::msg::Obstacle obstacle;
            geometry_msgs::msg::Polygon polygon;
            if (!buildClosedPolygonFromHull(convexHull, polygon))
            {
                RCLCPP_WARN(this->get_logger(), "%sConvex hull does not have enough vertices%s", kRed, kReset);
                continue;
            }

            obstacle.polygon = polygon;
            obstacle.id = index;
            obstacle.type = "NONE";

            obstacle_collection.obstacles.push_back(obstacle);

            index++;
        }
    }
    if (!obstacle_collection.obstacles.empty())
    {
        RCLCPP_INFO(this->get_logger(), "%sConvex hull markers published%s", kYellow, kReset);
        RCLCPP_INFO(this->get_logger(), "%sObstacle collection size: %zu%s", kYellow, obstacle_collection.obstacles.size(), kReset);
        obstacle_info_publisher_->publish(obstacle_collection);
    }
    else
    {
        warnUnsafePerception("Convex hull produced no valid obstacles; no obstacle update published.");
    }
}

void pointcloud_clustering_node::concave_hull(const std::vector<pcl::PointCloud<pcl::PointXYZ>::Ptr> &cloud_clusters)
{
    obstacle_collection.obstacles.clear();

    obstacle_collection.header.stamp = this->now();
    obstacle_collection.header.frame_id = FRAME_ID;

    int index = 0;
    obstacle_collection.obstacles.reserve(cloud_clusters.size());
    for (const auto &cluster : cloud_clusters)
    {
        auto selected_hull = std::make_shared<pcl::PointCloud<pcl::PointXYZ>>();
        bool use_convex_fallback = false;

        pcl::ConcaveHull<pcl::PointXYZ> concave_hull_builder;
        concave_hull_builder.setInputCloud(cluster);
        concave_hull_builder.setDimension(2);
        concave_hull_builder.setAlpha(CONCAVE_ALPHA);
        concave_hull_builder.reconstruct(*selected_hull);

        if (selected_hull->empty() || concave_hull_builder.getDimension() != 2 || selected_hull->points.size() < 3)
        {
            use_convex_fallback = true;
        }

        if (use_convex_fallback)
        {
            RCLCPP_WARN(this->get_logger(),
                        "%sConcave hull fallback to convex for cluster %d%s",
                        kRed, index, kReset);

            pcl::ConvexHull<pcl::PointXYZ> convex_hull_builder;
            selected_hull = std::make_shared<pcl::PointCloud<pcl::PointXYZ>>();
            convex_hull_builder.setInputCloud(cluster);
            convex_hull_builder.setDimension(2);
            convex_hull_builder.reconstruct(*selected_hull);

            if (selected_hull->empty() || convex_hull_builder.getDimension() != 2 || selected_hull->points.size() < 3)
            {
                RCLCPP_WARN(this->get_logger(), "%sConvex fallback hull is empty or invalid%s", kRed, kReset);
                continue;
            }
        }

        path_planning_dynamic::msg::Obstacle obstacle;
        geometry_msgs::msg::Polygon polygon;
        if (!buildClosedPolygonFromHull(selected_hull, polygon))
        {
            RCLCPP_WARN(this->get_logger(), "%sSelected hull does not have enough vertices%s", kRed, kReset);
            continue;
        }

        obstacle.polygon = polygon;
        obstacle.id = index;
        obstacle.type = "NONE";
        obstacle_collection.obstacles.push_back(obstacle);

        index++;
    }

    if (!obstacle_collection.obstacles.empty())
    {
        RCLCPP_INFO(this->get_logger(), "%sConcave hull markers published%s", kYellow, kReset);
        RCLCPP_INFO(this->get_logger(), "%sObstacle collection size: %zu%s", kYellow, obstacle_collection.obstacles.size(), kReset);
        obstacle_info_publisher_->publish(obstacle_collection);
    }
    else
    {
        warnUnsafePerception("Concave hull produced no valid obstacles; no obstacle update published.");
    }
}

void pointcloud_clustering_node::warnUnsafePerception(const std::string &warning_message)
{
    RCLCPP_WARN(this->get_logger(), "%s%s%s", kRed, warning_message.c_str(), kReset);
}



int main(int argc, char **argv)
{
    rclcpp::init(argc, argv);
    auto node = std::make_shared<pointcloud_clustering_node>();
    rclcpp::spin(node);
    rclcpp::shutdown();
    return 0;
}
