nmpc_controller_node:
  ros__parameters:
    h: 0.2
    N: 10
    L: 0.315
    v_max: 0.25
    a_max: 0.15
    lambda_1: 4.0 #suaviza cambios de aceleración entre ruedas. Subirlo ayuda contra comandos bruscos.
    lambda_theta: 0.2 #peso para seguir orientación. Si está alto, el robot intenta corregir yaw rápido.
    lambda_v: 0.03 #peso para seguir orientación. Si está alto, el robot intenta corregir yaw rápido.
    d_safe: 0.3
    voxel_size: 0.5
    max_range: 3.5
    max_obstacles: 20
    map_frame: "map"
    base_frame: "base_footprint"
    cmd_vel_topic: "/cmd_vel_nav"
    costmap_topic: "/occupancy_grid_obstacles"
    path_topic: "/sdv_trajectory"
    goal_tolerance: 0.1
